commitlint.config.cjs

commit lint config에서 `Cleanup` 키워드가 `Clanup`으로 되어있어 오타 수정했습니다.

[#13] Chore: commit lint 오타 수정

---

src/apis/auth/queryFn.ts
src/apis/auth/useLogin.ts
src/apis/auth/useRegister.ts
src/components/Layout/Modals/Base/form.tsx
src/components/Layout/Modals/Login/index.tsx
src/components/Layout/Modals/Register/config.ts
src/components/Layout/Modals/Register/index.tsx
src/components/common/Mention/MentionInput.tsx
src/components/common/Mention/UserBadgeList.tsx

- 회원가입 폼에 닉네임 인풋 추가
- 비밀번호 확인 인풋 추가 및 비밀번호와 비밀번호 확인 값 같은지 검사 추가
- 회원가입 api 구현 및 연결
- 회원가입 성공 시 로그인 모달 띄우기, 실패 시 alert 창 띄우기
**작업내용 외 전달 사항**
- 에러 처리는 상세하게 구현하지 않았습니다. (후에 common modal 같은거 적용 생각 중 입니다!)
- 인풋 유효성 검사는 성빈님이 구현해주신 것을 그대로 사용했습니다.
- 프로필 이미지 첨부는 회원가입 api request body에 없어 구현하지 않습니다. 프로필 이미지 변경 api만 있는데 여기에 토큰 값이 필요하여 회원가입 때는 구현이 필요 없고 프로필 정보 변경 때 구현해야할 것 같다고 생각했습니다.!
- 질문 사항
에러 처리를 간단하게 하던 도중 아래와 같은 에러가 발생했습니다! 
`AxiosError` 타입을 이용하여 에러 객체를 정의하고 있는데 `isAxiosError`, `toJSON` 프로퍼티가 없다고(?) 하는 것 같은데 이를 어떻게 해결해야할지 모르겠습니다..! 그래서 우선은 타입 단언으로 해결했습니다 ..!
```ts
// src/components/Layout/Modals/Register/index.tsx
// line 32
const register = useRegister();
const error: AxiosError<string> = register.error;
alert(error.response?.data);
// Error
// Type 'Error' is missing the following properties …
```

[#16] Feat: 회원가입 로직 구현

---

src/App.tsx
src/apis/auth/queryFn.ts
src/apis/auth/queryKey.ts
src/apis/auth/useGetUserInfo.ts
src/main.tsx

- ~스토어에 저장된 user 객체가 없는 경우(null) 로컬 스토리지에 저장된 token을 이용해 유저 인증 api를 조회하여 다시 저장하는 로직을 구현했습니다.~
- 로컬 스토리지에 토큰이 있기 때문에 유저 정보는 api를 통해 불러올 수 밖에 없는 상황압니다. 어차피 유저 정보를 불러와야 하는데 스토어에까지 저장을 해야하는지에 대한 의문과 유저 정보를 어디서 불러와야 하는지에 대한 고민으로 우선 유저 정보를 불러오는 훅만 구현했습니다.!
- 새로고침 시 해당 라우트에서 유저 정보가 스토어에 있는지 확인하려면 App에서 접근을 해야하기 때문에 App에 코드를 작성했습니다.
- 따라서 App에서 리액트 쿼리를 이용해 유저 인증 api를 조회해야 하기 때문에 `QueryClientProvider` 태그를 main으로 옮겼습니다.
- 이 로직을 구현하는 것이 처음이라 여러 방법을 고민해보았는데, 최상위를 수정하는 방법 밖에 떠오르지 같아 최상위 컴포넌트들을 수정했습니다. 근데 최상위 만큼은 프로젝트 진행 단계에 수정하고 싶지 않았던지라 ,, 다른 좋은 방법이 있으면 그 방법에 맞게 수정해보겠습니다!!
- 스토어에 저장된 user 객체와 로컬 스토리지에 저장된 token 문자열에 따라 쿼리를 실행할 수 있도록 `enabled`에 넣었는데도 실행이 되는 것 같습니다..! [캐싱된게 없을 때는 pending 상태인 것](https://tanstack.com/query/latest/docs/react/guides/disabling-queries)으로 이해했는데, 제가 잘못 이해한 것인지 혹은 조건을 잘못 넣은 …

[#36] Feat: 로그인 후 새로고침 했을 때 유저 정보 다시 불러오는 로직 구현

---

src/components/Layout/Modals/Register/index.tsx

`useEffect`를 통해 회원가입 쿼리 실행 후 반환되는 성공 여부에 따라 `handleLoginClick` 함수를 실행하게 했는데 `handleLoginClick`이 계속 새롭게 할당되어 `useCallback`을 통해 최적화를 했습니다. `handleLoginClick`은 `open` 상태를 계속 토글하는 로직을 갖고 있습니다. 이 때문에 `useCallback`의 의존성 배열에 `open`이라는 상태가 들어가있어 토글이 되면 계속 감지하고, 새로 할당되어 무한루프가 발생했기 때문에 버벅임 현상이 발생한 것 입니다.
(만약 잘못 설명한 부분이 있다면 지적 부탁 드립니다!)
따라서 회원가입 모달에서 로그인 모달로 넘어가는 경우는 `회원가입 모달 닫기 + 로그인 모달 열기`이기 때문에 `open` 상태를 토글할 필요가 없다고 생각하여 고정값인 `false`로 상태를 변경해주었습니다.
아래는 테스트를 위해 작성한 코드 입니다.! 이슈에도 첨부했습니다 :D
계속 api를 실행하기엔 비용이 큰 것 같아 함수를 트리거할 새로운 상태를 만들어 테스트했습니다!
```ts
// given
const [isTrigger, setIsTrigger] = useState(false);
const handleLoginClick = useCallback(() => {
console.log("handleLoginClick", open);
toggleOpen(!open);
openLoginModal(true);
}, [open, toggleOpen, openLoginModal]);
const handleLoginClick1 = …
```

[#61] Fix: 회원가입 시 로그인 모달 버벅임 버그 해결

---

src/apis/auth/useLogin.ts
src/components/Layout/Modals/Login/index.tsx

로그인 후 성공/실패 여부에 상관 없이 모달 닫는 기능을 구현했습니다.
`useLogin` 훅에 `toggleOpen` 함수를 props로 넘겨줄지(현재 코드) 혹은 쿼리가 반환하는 `isSettled` 값을 사용할까 고민했습니다.
큰 상관은 없지만 `isSuccess`, `onSuccess`같은 것들을 어떤 상황에서 쓰는시지 조금 궁금해졌습니다,,
close #63

[#63] Feat: 로그인 후 모달 닫기

---

src/components/MyThreads/MyThreadBody.tsx

기존 store에서 user정보 받아오던 로직에서 새로고침 시 유저정보가 유지가 되지않던 이슈가 있어서
커스텀 훅으로 react query가 항상 로컬스토리지 토큰에서 유저 정보를 받아오도록 수정합니다.
close #65

[#65] Modify: 내가 쓴 글에서 커스텀훅으로 user정보 받아오도록 로직 변경

---

src/components/Demo/ExEditorTextArea.tsx
src/hooks/api/useEditorLogicByProps.ts
src/hooks/api/useMentionNotification.ts
src/hooks/api/useUploadComment.ts

멘션시와 알림 시 오류가 있어서 수정했습니다. 
1. notificationType : MENTION => MESSAGE
2. comment 알림 대상 => 자신으로 되어있어서 post 작성자로 변경

Fix: comment 알림의 대상, 멘션 타입 수정

---

src/components/Layout/Modals/Base/form.tsx
src/components/Layout/Modals/Base/modal.tsx
src/components/Layout/Modals/Setting/ImageUploadForm.tsx
src/components/Layout/Modals/Setting/config.ts
src/components/Layout/Modals/Setting/index.tsx
src/components/Layout/Sidebar/ThemeConfigDropdown.tsx

- 이전 성빈님이 작업하신 모달과 비슷한 코드로 작성했습니다.
- 프로필 편집 모달 인풋에는 수정 불가능한 것들이 있기 때문에 수정이 불가능하면 default value를 지정하려고 했습니다. 그러나 만드신 공통 input에는 value와 handler 함수가 항상 들어가다보니 value와 default value 가 같이 들어가면 경고가 떠 value로 통일하고 readonly 속성도 함께 사용했습니다.! 만약 잘못된 해결 방법이라면 리뷰 달아주세요 :)
- 프로필 편집 모달이 길어져 최대 높이와 스크롤을 추가했습니다.
- 유효성 검사는 아직 세세하게 다루지 않았습니다.
- 모달을 최상단에 두어 zustand와 관리하는 것은 나중에 한번에 리팩토링 하겠습니다!
- 사진 첨부하는 부분은 children props으로 받아오게 했는데 좋은 방법인지 모르겠네요!
- 코드 전반적으로 가독성이 좋은지, 잘 짜여진 코드인지 궁금합니다.
close #72

[#72] Style: 프로필 편집 모달 UI 퍼블리싱

---

src/App.tsx
src/components/Demo/ExThreadDetailView.tsx
src/components/common/thread/CommentListItem.tsx
src/components/common/thread/ThreadDetailView.tsx

resolves #33 
Visit: https://fedc-5-dev-namu-eunsu-git-33-featurethread-de-70c95b-devnamu-v1.vercel.app/detail

[#33] Feat: 스레드 자세히 보기

---

src/apis/auth/queryFn.ts
src/apis/auth/usePutProfile.ts
src/components/Layout/Modals/Base/form.tsx
src/components/Layout/Modals/Base/modal.tsx
src/components/Layout/Modals/Setting/config.ts
src/components/Layout/Modals/Setting/index.tsx

~사진 업로드 구현이 되지 않았지만 시간 상 맞지 않는다면 이후로 넘어가도 좋다고 하셔서 draft로 올렸습니다.!~
~오늘 내로 어려울 것 같으면 사진 첨부 관련 부분 커밋은 삭제 후 draft 해제하겠습니다.~
~프로필 사진 로직 코드가 추가되어도 작업 완료한 부분 코드는 수정하지 않을 것 같아 코드를 읽으시는데 상관 없어서 draft로 미리 올렸습니다.~
테스트는 로그인 이후 사이드바에서 시스템 열면 가능합니다! :D
프로필 사진 변경 로직은 api 훅에 추가해두었지만 모달 쪽에서 구현이 되지 않아 이미지 업로드 컴포넌트만 view에서 삭제해두었습니다 :D
- 유저가 프로필 변경하기 위해 모달을 열 때 유저 정보(이름, 이메일, 닉네임) 불러와 인풋에 채워넣기
- 인풋 폼 유효성 검사
- 닉네임 글자 수가 1개 이상이어야지 허용
- 비밀번호는 8자 이상 입력해야 하며 입력 안한 경우에는 유효성 검사를 하지 않음
- 비밀번호와 비밀번호 확인 인풋에 같은 값이 들어갔는지 검사, 둘 다 0글자 입력했을 때는 검사 안함
- 프로필 닉네임 변경 api 연결
- 예전 닉네임과 같은 경우에는 api 호출하지 않음
- 비밀번호 변경 api 연결
- 비밀번호 내용이 있는 경우에만 호출
- 유효성 검사 부분에서 닉네임이 "프롱이"로 되어있을 시에는 회원가입 할 때 닉네임을 입력하지 않은 것이므로 닉네임을 필수로 변경하게끔 로직을 수정해야할까요?
- 놓친 유효성 검사가 있는지 궁금합니다.
- 그 외 편하게 리뷰 주시면 감사하겠습니다 :D
close #81

[#81] Feat: 프로필 변경 로직 구현

---

package.json
src/apis/thread/queryFn.ts
src/apis/thread/usePostThreadLike.ts
src/components/common/thread/ThreadListItem.tsx
src/constants/notification.ts
src/hooks/api/useLikeThread.ts
src/hooks/api/useMentionNotification.ts
src/hooks/api/useUploadComment.ts
src/pages/Home/index.tsx
yarn.lock

- 좋아요 요청 커스텀 훅과 알림 보내기 커스텀 훅을 사용하여 새로운 커스텀 훅 구현(useLikeThread)
- 기존에 문자열로 사용하던 `notificationTypes`를 상수화하여 타입 단언을 제거하고 자동 완성이 되도록 했습니다.
- nanoid 설치(yarn install을 새로 해주셔야 합니다!!)
- 낙관적 업데이트를 할때, 좋아요 객체를 생성하여 넣어주어야 합니다. 성공하면 새로 요청을, 실패하면 롤백을 하기 때문에 `_id`를 nanoid로 생성하여 넣어주었습니다.
- nanoid를 사용하지 않고 빈 문자열로 해두어도 문제가 되진 않지만 혹시 몰라 고유 id를 생성하여 넣어주었습니다.
이상한 부분 지적해주시면 수정하겠습니다!
close #87

[#87] Feat: 좋아요 알림 api와 커스텀 훅 구현 및 적용

---

src/components/MyNotifications/LikeNotification.tsx
src/components/MyNotifications/MyNotificationBody.tsx
src/components/MyNotifications/MyNotificationItem.tsx
src/types/notification.ts
src/types/thread.ts

내 알림에 like, comment, mention 3가지 경우가 있음 
- like를 취소할 경우 like : null로 변경됨 => null일 경우 error
- null이 아닐 경우만 처리 하도록 타입가드로 해결 
- mention할 경우 Notification, Conversation 둘다 mention 필드가 있음 
- 실제로 처리해야하는 경우는 Conversation
- Notification에는 messageId, Conversation : message[] 가 넘어옴 
- JSON.parse가 가능한 경우만 처리하도록 타입가드로 해결 
- Notification의 Like 타입의 post는  Like 생성, 삭제와 다른 값이 넘어와서 새로운 타입을 추가했습니다. (LikeByNotification)
빠르게 버그 잡느라 타입단언도 사용하고 코드가 지저분합니다. 배포이후 리팩토링 해야합니다!!
close #101

[#101] Fix: 내 알림에 아무것도 없을 시 에러처리

---

src/App.tsx
src/apis/auth/useLogin.ts
src/apis/auth/usePostLogin.ts
src/components/Layout/Modals/Login/index.tsx
src/components/Layout/Modals/Register/index.tsx
src/constants/authError.ts
src/hooks/api/useUpdateUserList.ts

- 성공/실패 시 토스트 메시지 띄우게 처리([shadcn sooner](https://ui.shadcn.com/docs/components/sonner) 이용)
- 성공한 경우에만 모달 닫히도록 처리
- 로딩중, 성공, 실패 메시지 상수 설정
- `toast.promise(func, ...)`에 프로미스를 반환하는 함수가 들어가야해서 `mutateAsync` 사용(`mutate`는 `void` 반환)
- 로그인 쿼리에서는 `mutateAsync`만 사용하여 재훈님이 작업하신 부분과 함께 간단한 리팩토링을 했습니다.
- `usePostLogin` 커스텀 훅에서 `return { login: mutateAsync }`으로 반환하여 바로 `login`으로 mutate 할 수 있도록 처리했습니다.
- 변수명, 메시지 문구 적절한지 부탁드립니다!
- 성공 메시지들도 상수 처리 하는게 좋은지 고민입니다!
- [sooner Docs](https://sonner.emilkowal.ski/)에서 여러 메시지나 포지션을 지원하는데 한번 보시고 다르게 고쳐도 될 것 같다 하시면 편하게 말씀 주세요!
- toast.promise는 따로 utils로 빼서 메서드처럼 사용하게 만들까 고민 중 입니다! :D (프로필 변경도 처리해야해서 이 업무 후 할 것 같습니다)
close #41

[#41] Feat: 회원가입, 로그인 모달에서 에러 경고, 혹은 성공 토스트 메시지 처리

---

src/components/MyNotifications/MyNotificationBody.tsx
src/components/MyNotifications/MyNotificationItem.tsx
src/components/MyThreads/MyThreadBody.tsx
src/components/common/myactivate/emptyThread.tsx

빈 리스트 시 사용자가 알 수 있도록 문구를 표기합니다.
기존에 내 알림에서 어떤 채널에서 댓글이 달리고 멘션이 되었는지 채널이 제대로 매칭되지 않아 수정하였습니다.
close #108

[#108] Feat: 내 알림, 내가 쓴 글이 비어있을 시 디폴트 내용 출력

---

src/App.tsx
src/components/common/EditorTextArea.tsx
src/components/common/mention/MentionInput.tsx

1. 스레드의 content와  폰트 사이즈 통일 
2. 비회원이 에디터 입력 시  → alert(로그인 필요함) -> 로그인/회원가입 모달로 이동
3. 익명이름 없을 경우 익명 클릭 시-> 내 프로필 편집 모달로 이동 
제가 작성한 코드가 거의 없습니다ㅎ 
변경 사항인 User 여부와 모달은 
1.  로그인 판단
User 객체 존재 여부는 에디터에서 판단하는게 아닌 에디터를 보내주는 쪽에서 이미 User객체가 있기 때문에 받아와서 사용하는게 좋을 것 같습니다. 
하지만 현재 에디터 자세히보기 구현코드가 합쳐지지 않은 상태라 그냥 에디터에서 불러왔습니다. 
배포 이후 props로 넘겨주는 식으로 변경하는게 좋을 것 같습니다!
2. 모달 띄우기
여러곳에서 사용하는 모달은 Layout이나 App단으로 띄우고 사용하는곳에서는 트리거만 이용하기로 결정된것로 알고있습니다! 
하지만 이부분도 배포이후에 작업하기로 하였기 때문에 현재 에디터에서 sideBar의 코드를 그대로 가져오 모달을 다 불러오고(로그인, 회원가입, 정보변경) 처리하게 되었습니다.
이부분도 배포 이후 전역으로 오픈여부를 관리하며 에디터에서는 트리거 역할만 하도록 변경하는게 좋을 것 같습니다!! 
close #105

[#105] Feat: QA 이후 배포 전 EditerTextArea 수정사항 반영

---

src/components/common/thread/ThreadListItem.tsx
src/components/common/thread/ThreadToolbar.tsx
src/hooks/common/useToast.ts

- useToast 훅을 구현
- showToast와 프로미스 show Toast 함수 구현
- 좋아요 클릭시 토스트 렌더
- 토스트에서 로그인 클릭시 로그인 모달 띄우도록 구현
- 윤서님께서 toast.promise를 사용하고 계셔서 showPromsieToast도 구현했습니다.
- 간단히 테스트 해봤는데 되는 것 같긴한데 문제가 없는지 봐주시면 감사하겠습니다 : )
close #118

[#118] Feat: use toast hook 구현 및 좋아요 클릭시 토스트 적용

---

src/components/common/EditorTextArea.tsx
src/pages/Home/index.tsx

- 원래 x 버튼을 띄우려다가 멘션을 취소하느 느낌이 들어서 슬랙과 동일하게 취소, 확인 버튼으로 수정했습니다.
- 에디터에 길게 쓰면 익명 창 넘어까지 글이써져서 px를 줘서 막았습니다. 
- 스크롤도 숨겼어요
- 빠르게빠르게하느라 에디터에 너무 하드 코딩 되었습니다... onClose 유무로 판단하고 있어서 이정도로 분기처리되는게 많으면 에디터 하나로 모든 걸 처리하기보다 합성컴포넌트로 만들거나 createThread, patchThread, commentThread 따로따로 만들어서 사용해야 할 것 같습니다.
close #143

[#143] Feat: 기존 스레드 수정 시 EditorTextArea 띄우면 x 버튼으로 추가

---

src/components/MyNotifications/MyNotificationBody.tsx
src/components/MyThreads/MyThreadBody.tsx

- 내 알림과 내가 작성한 글 페이지에 높이가 지정되어있지 않아 가운데이 위치하지 않아 위/아래 패딩과 제목 높이를 가늠해서 지정해주었습니다.
- 브라우저 높이를 줄이면 텅... 문구가 제목을 침범하여 최소 높이를 지정해주었습니다.
- 편하게 리뷰 주시면 감사하겠습니다 :D
close #138

[#138] Style: 내 알림, 내가 작성한 글 페이지에 비어있는 경우 "텅" 글자가 가운데 오도록 스타일 변경

---

src/components/Layout/Sidebar/index.tsx
src/components/MyNotifications/CommentNotification.tsx

댓글 삭제 시 내 알림에서 파싱에러가 발생하여 try catch문으로 해결했습니다.
close #154

[154] Fix: 삭제된 댓글에 대하여 파싱에러 해결

---

src/apis/comment/useDeleteComment.ts
src/apis/thread/usePutThread.ts
src/components/common/EditorTextArea.tsx
src/components/common/thread/CommentListItem.tsx
src/components/common/thread/ThreadDetailView.tsx
src/components/common/thread/ThreadListItem.tsx
src/components/common/thread/ThreadToolbar.tsx
src/hooks/api/useChangeThread.ts
src/hooks/api/useEditorLogicByProps.ts
src/hooks/api/useUpdateUserList.ts

- 편집 버튼 클릭시 해당 리스트만 에디터로 변환
- 편집 취소, 편집 저장하면 에디터에서 리스트로 변환하기 위한 set함수를 `EditorTextArea` 컴포넌트에 props로 전달
- usePutThread 성공시 쿼리키 invalidate
편집 저장시, 변경된 내용이 저장이 안되고 리스트가 삭제되고 있습니다...
이슈 처리 도와주십쇼
close #127

[#127] Feat: 편집 버튼 클릭시 에디터로 변환

---

src/components/Layout/Sidebar/index.tsx
src/components/common/thread/ThreadDetailView.tsx
src/components/common/thread/ThreadListItem.tsx

- 스레드 리스트 아래에 댓글 개수 표시
- 게시판에서 보이는 스레드 줄 수 제한 (3줄)
- 스레드 상세보기에서 thread.channel이 undefined인 경우 처리
UI 갠춘한가요?
close #158

[#158] Feat: 스레드 리스트 아래에 댓글 개수 표시

---

src/components/common/thread/ThreadDetailView.tsx
src/components/common/thread/ThreadListItem.tsx

스레드 상세보기와 스레드 리스트가 같은 컴포넌트를 사용합니다.
props로 상세보기인지 판별하는 변수를 받아 상세보기일 경우는 말줄임을 삭제합니다.
더 좋은 방법이 있다면 알려주십쇼!!
close #170

[#170] Fix: 스레드 상세보기에서 말줄임 제거

---

src/apis/auth/queryFn.ts
src/apis/auth/usePutProfile.ts
src/components/Layout/Modals/Profile/ImageUploadForm.tsx
src/components/Layout/Modals/Profile/index.tsx
src/components/common/thread/CommentListItem.tsx
src/components/common/thread/ThreadDetailView.tsx
src/components/common/thread/ThreadListItem.tsx
src/constants/commonConstants.ts
src/constants/toastMessage.ts

(500 에러난다고 했던 부분은 .. FormData에 키 값이 맞지 않아 난 에러였답니다 .. 총총)
- 프로필 이미지 업로드는 사진 첨부 시 바로 api 통신
- 성공 시 이미지 미리보기 + 토스트 메시지 띄워짐, 실패 시에는 토스트 메시지만 출력
- 드래그 앤 드랍으로 이미지 첨부 가능
- 프로필이 있는 유저 + 기명으로 작성한 경우 스레드, 댓글에 프로필 이미지 나오도록 처리
프로필 삭제하는 기능이 현재 제공되는 api에서 구현되고 있는 것 같지 않아 이미지 제거 버튼 삭제했습니다.
삭제하는 경우에는 
```ts
const formData = new FormData();
formData.append("image", new File([], ""));
```
이런 식으로 formData에 넣어봐도 이미지를 넣으라는 400 에러가 떠서 삭제 기능은 구현하지 않았는데 혹은 제가 잘못된 방법으로 구현한 것인지 궁금합니다.
close #98

[#98] Feat: 프로필 사진 변경 기능 구현

---

src/apis/auth/usePostLogout.ts
src/components/Layout/Sidebar/view.tsx

로그인 모달을 통해 로그인 했을 때와 새로고침, 재방문 시 자동 로그인 했을 때의 토스트 메시지를 분리 했습니다.
- 로컬 스토리지를 통해 토큰이 있는데 로컬 스토리지에 저장된 `isLogin` 값이 없거나 false인 경우
- 로그인 모달로 로그인 한 것으로 스토리지에 true로 저장 + 로그인 성공 메시지
- 로컬 스토리지를 통해 토큰이 있는데 로컬 스토리지에 저장된 `isLogin` 값이 true인 경우
- 자동 로그인으로 인지 > 자동 로그인 메시지
- 로그아웃 시 `isLogin` 값을 삭제했습니다.
- 로직이 맞는지 궁금합니다.
close #188

[#188] Modify: 로그인/자동 로그인 토스트 메시지 분리

---

package.json
src/components/MyNotifications/CommentNotification.tsx
src/components/MyNotifications/LikeNotification.tsx
src/components/MyNotifications/MentionNotification.tsx
src/components/MyThreads/MyThreadItem.tsx
src/utils/formatDateFns.ts
yarn.lock

date-fns 라이브러리를 설치하고 함수를 추가하였습니다.
기존의 데나무숲은 DateFormat함수를 활용하여 하루가 지난 글은 모두 "n년n월n일" 의 형식으로 표현하였습니다.
새로 추가된 DateFormatFns 함수를 활용하면 3일 전까지 표시가 가능합니다.
기존) 해당 일의 글 = n시 n분
이전 일의 글 = n년 n시 n분
변경) 24시간 이내의 글 = 방금 전, n시간 전
1일~3일 이내의 글 = n일 전
3일 보다 오래된 글 =n년 n시 n분
새 라이브러리가 추가되었으니 install 부탁드립니다!
close #196

[#196] Modify: 날짜 포맷팅 함수 변경

---

src/apis/comment/useDeleteComment.ts
src/apis/comment/usePostComment.ts
src/components/common/EditorTextArea.tsx
src/components/common/thread/ThreadDetailView.tsx
src/hooks/api/useEditorLogicByProps.ts
src/hooks/api/useUploadComment.ts

댓글 추가, 삭제시 스레드 상세보기의 query key invalidate 해주고 있어서
리스트의 query key도 invalidate 처리 해주었습니다.
수정사항 있으면 알려주세요!
close #201

[#201] Fix: 댓글 추가, 삭제시 리스트 query key invalidate

---

package.json
src/components/Layout/Modals/Login/index.tsx
src/components/Layout/Modals/Profile/ImageUploadForm.tsx
src/components/Layout/Modals/Profile/index.tsx
src/components/Layout/Modals/Register/index.tsx
src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
src/components/Layout/Sidebar/view.tsx
src/components/common/EditorTextArea.tsx
src/components/common/mention/MentionInput.tsx
src/components/common/thread/ThreadListItem.tsx
src/hooks/api/useToggleLike.ts
src/pages/Error/index.tsx
src/pages/MyNotifications/index.tsx
src/pages/MyThreads/index.tsx
src/pages/NotFound/index.tsx
vite.config.ts
yarn.lock

resolves #202 
- Sentry에서 `type:info`로 집계해도 Error 개수에 들어가던 `Sentry.captureMessage`에서 GA4의 Event로 전환 (GA4 대시보드에서 확인)
- GA4의 전환 추적 등의 기능에 사용
- 로컬에서 정상 동작 확인
- Vite config에서 `VITE_` 가 필요 없는 경우 `loadEnv`가 필요 없어서 지웠습니다 (.env 파일을 읽는 경우가 아니어서 필요 없음)
- PR 일부에서 className 정렬 변경 사항도 같이 포함되어 있습니다. (단순 prettier --write)
- prettier lint가 안 된 상태 혹은 잘못 정렬된 상태(이유는 모르겠지만)로 통과하는 것 같은데 `prettier`가 아닌 `prettier --check`로 명령어 변경할게요(prettier로 포매팅 가능한 내용 있으면 warning 표시됨) -> 인지하셨으면 해당 pr에서 husky 바꿀게요
- <img src="https://github.com/prgrms-fe-devcourse/FEDC5_DevNamu_eunsu/assets/28754907/408b559d-521a-4fee-9571-64ff27128820" width=500>

[#202] Refactor: Sentry -> GA4 로그 수집 위치 변경

---

vite.config.ts

resolves #215 
GA4 script를 개발 환경에서는 로딩하지 않는 오류를 해결함
원인
- Vite plugin이 enableDev: false 혹은 GA4 ID가 없는 경우 script를 추가하지 않음
해결 방법
- 환경 변수 이름의 prefix에 `VITE_`를 추가해 env 파일에서 로딩
- 개발 환경에서도 로딩하되 전송만 하지 않게 `disable` 옵션을 배포 환경이 아닐 때 활성화

[#215] Fix: GA4 script를 개발 환경에서는 로딩하지 않는 오류 

---

src/apis/auth/usePostLogout.ts
src/apis/thread/useGetThreads.ts
src/components/Layout/Modals/Information/index.tsx
src/components/Layout/Modals/Login/index.tsx
src/components/Layout/Modals/Profile/index.tsx
src/components/Layout/Sidebar/view.tsx

내 정보 수정과 내 프로필 편집 문구 통일이 안되어있음 
> 내 정보 수정으로 통일했습니다
로그인 후 강제 새로고침이 되어 로그인이 되었습니다 메시지가 무시당하고 바로 자동로그인 되었습니다 메시지가 뜸
> 로그인 후 나오는 성공 메시지는 삭제하고 새로고침 후 자동 로그인 말고 로그인 되었습니다 메시지만 노출되게 수정
안내 모달에 잡담 게시판 설명 추가
사용 > 이용으로 단어 통일
close #218

[#218] Fix: 로그인, 내 정보 수정 모달 수정

---

src/apis/comment/useDeleteComment.ts
src/apis/comment/usePostComment.ts
src/components/common/thread/CommentListItem.tsx
src/components/common/thread/ThreadListItem.tsx
src/hooks/common/useToast.ts

저희 프로젝트의 특이점은 스레드 작성, 스레드 리스트, 스레드 상세보기를 한 화면에서 볼 수 있다는 것입니다. 따라서, 댓글이 추가될때 상세화면만 반영이 이루어져야 하는 것이 아니라 스레드 리스트 부분에도 변경이 일어나야 합니다.
그러다보니, 하나의 작업임에도 두 개의 쿼리 키를 invalidate하여 새로 데이터를 받아와야 합니다. 기존에는 댓글 작성 및 삭제시 성공했을때 스레드 리스트의 쿼리 키와 스레드 상세의 쿼리 키를 invalidate 처리만 해주고, 재요청 받은 데이터를 UI에 반영합니다.
스레드 상세의 요청의 경우 속도가 크게 느리지는 않지만 문제는 스레드 리스트의 경우입니다. 이 경우 불러오는 리스트의 양이 많다보니 시간이 오래 걸리게 되는데, slow 3G 환경의 경우 최대 10초가 넘는 시간을 기다려야 UI에 반영이 되었습니다.
아래 영상을 보시면 10.61초가 걸린 후에야 스레드 리스트 쪽에 변경이 일어난 것을 알 수 있습니다. 현재 저희 프로젝트는 timeout을 10초로 제한해두었는데, 지금처럼 10초가 넘어가게 되면 한 번 더 요청이 가므로 최악의 경우 10초 이상의 시간이 걸립니다.
https://github.com/prgrms-fe-devcourse/FEDC5_DevNamu_eunsu/assets/61978339/138ebc16-579a-425c-ad54-f5d46f52106f
따라서, react query의 setQueryData를 사용하여 요청이 성공하게 되면 수동으로 데이터를 변경해주어 쿼리 키가 invalidate 되고 요청을 받아오지 않아도 되게끔 변경해주었습니다. …

[#226] Fix: 댓글 추가, 삭제시 ui 반영 속도 개선

---

src/apis/thread/useGetThreads.ts
src/components/Error/ApiError.tsx
src/components/Error/thread/ThreadError.tsx
src/components/common/thread/ThreadDetailView.tsx
src/hooks/api/useThreadsByChannel.ts
src/pages/Home/index.tsx

1. ApiError 컴포넌트 UI 작업
처음에 스레드쪽에서만 사용하려고 컴포넌트 이름을 `ThreadError`라고 지었다가, 모든 api 요청 실패 경우에 사용할 수 있을 것 같아 `ApiError`로 변경했습니다. 좋은 이름인지는 잘 모르겠습니다. 추천해주시면 좋을 것 같아요.
2. ThreadList와 ThreadDetailView에 적용
만들어든 컴포넌트를 두 곳에 적용했습니다. refetch는 필수로 받아 아이콘 클릭시 다시 호출하도록 구현했습니다.
객관적으로 이쁜 UI는 아니에요! 뭔가 이뻐질 수 있는 좋은 아이디어 받습니다~~
추가로 컴포넌트 이름이 `ApiError`가 최선인가에 대한 생각이 계속 들어요. 적절한 이름 추천해주시면 감사하겠습니다.
close #230

[#230] Style: 스레드 리스트, 상세보기 요청 실패시 보이는 에러 컴포넌트 구현 및 적용

---

src/apis/thread/useDeleteThread.ts
src/apis/thread/usePostThread.ts

api 응답 속도가 느려, 요청 성공시 응답을 기다리지 않고 setQueryData로 즉시 변경했습니다.
앞서, 댓글의 경우 반영 속도가 느려 토스트를 띄워줬었는데 스레드의 경우 반영 속도가 빨라 토스트를 따로 띄우지 않았습니다.
그런데 삭제의 경우, 모달을 한 번 띄워주는게 좋을 것 같다는 생각이 드네요.
슬랙의 경우 삭제 버튼의 접근이 어렵지만 저희는 마우스를 호버하면 삭제 버튼이 바로 노출되기 때문에 모달로 인지시켜주는게 좋을 것 같습니다.
onSuccess로 넘어오는 데이터는 파싱되기 전, 서버 응답 값이더라구요. 때문에 `onSuccess`에서 데이터를 파싱하는 로직이 중복으로 들어가게 되었습니다.
이렇게 되다보니 전에 재훈님 말씀처럼 axios interceptors에서 파싱하는 방법이 더 좋을 것 같다는 생각이 듭니다.
많은 의견 주시면 감사하겠습니다!
close #228

[#228] Fix: 스레드 작성 및 삭제시 UI 즉시 업데이트
