package.json
src/App.tsx
src/Layout.tsx
src/components/Layout/Sidebar.tsx
src/components/Layout/index.tsx
src/pages/Home/index.tsx
src/pages/MyNotifications/index.tsx
src/pages/MyThreads/index.tsx
src/pages/NotFound/index.tsx
yarn.lock

resolves #1
1. lint-staged 설정 변경: prettier 대상을 `전체` -> `ts, tsx, css, json, html`로 한정시킴 (미지원 확장자 있으면 오류남)
2. React-router 설정
3. React-query 설정 및 Devtools 추가

[#1] React-router 및 React-query 초기 설정

---

.husky/commit-msg
commitlint.config.cjs
package.json
yarn.lock

resolves #2 
commit 시 commitlint 규칙을 강제해 git commit convention을 유지한다.
다음 허용된 type만 commit에 사용할 수 있다: `"Feat", "Fix", "Docs", "Style", "Refactor", "Test", "Chore", "Modify", "Rename", "Clanup"`

[#2] Commitlint 팀 규칙에 맞게 설정

---

index.html
public/background-gradient.css
src/components/Layout/Sidebar.tsx
src/components/Layout/Sidebar/DarkModeDropdown.tsx
src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
src/components/Layout/Sidebar/config.ts
src/components/Layout/Sidebar/index.tsx
src/components/Layout/Sidebar/styles.ts
src/components/Layout/Sidebar/view.tsx
src/components/Layout/index.tsx

레이아웃 및 사이드바 퍼블리싱
참고 사항
- 단순 PC 환경만 고려
- 내 알림의 버블에 대한 트랜지션은 아직 만들지 않았음
- 정상 동작을 위해선 
- 다음의 전역 상태 연동 필요:
- 현재 세션의 사용자 정보
- 현재 선택된 테마
- API 연동 필요:
- Notification API 연동으로 알림 개수 표시 필요
코드 리뷰 사항
- Tailwind CSS의 재사용 방법 (주석 참고)

[#8] Style: 사이드바 및 레이아웃 퍼블리싱

---

src/apis/core.ts

axios interceptors를 사용하여 response를 가공했습니다.
기존에 `response`로 반환하여 커스텀 훅에서 데이터를 사용할때 `data.data`로 접근해야 했는데, `response.data`를 반환함으로써 `data`로 접근하도록 했습니다.
close #26

[#26] Feat: axios interceptors를 사용하여 repsonse 가공

---

src/types/channel.ts
src/types/notification.ts
src/types/thread.ts
src/types/user.ts

어플리케이션 전반에서 사용하게 될 여러가지 response type들을 선언했습니다.
선언한 response 타입들은 아래와 같습니다.
- channel: Channel
- notification(알림 관련): Notification, Follow, Conversation, Message
- thread: 좋아요, 댓글, 스레드
- user: 유저 repsonse type
close #30

[#30] Feat: response types 선언

---

src/apis/auth/queryFn.ts
src/apis/auth/useLogin.ts
src/components/Layout/Modals/Login/index.tsx
src/stores/user.ts

- 로그인 api 구현(axios + react-query)
- 토큰 로컬 스토리지에 저장
- 전역 상태관리에 유저 정보 저장
- 로그인 폼 값 받아와 api 통신 연결
- 상태관리에는 불변한 것들(예를 들면 user id)만 저장할까 했는데 우선은 유저의 `id`, `email`, `name`, `nickname`, `token`을 저장했습니다. 저장할 필요가 없는 것들이 있는지 궁금합니다.
-  `isLoggedIn` 상태를 추가하여 로그인 여부를 추가로 저장합니다.
- `logout` 메서드(액션)을 구현했습니다.
- 변수명, 로직 등 더 개선할 사항이 있는지 궁금합니다.
- 로그인 실패 시 에러 처리는 아직 구현하지 않았습니다.
close #17

[#17] Feat: 로그인 로직 구현 및 api 연결

---

src/components/MyThreads/ThreadBody.tsx
src/components/MyThreads/ThreadHeader.tsx
src/components/MyThreads/ThreadItem.tsx
src/pages/MyThreads/index.tsx

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
내가 쓴 글 ui를 MyThread 디렉토리에 작업하였습니다.
첫 pr입니다... 짧은 코드이나 컨벤션 등 수정할 게 있는지 알려주시면 감사하겠습니다.
close #24

[#24] Feat: 내가 쓴 글 ui 구현

---

src/apis/thread/queryKey.ts

바뀐 파일명으로 parsingJson.ts import
앞의 공백이 없도록 변경했습니다.
close #45

[#45] Rename: 바뀐 파일명으로 import

---

package.json

resolves #58
package.json 내용 변경
AS-IS:
```json
"lint-staged": {
"*.{ts, tsx}": "eslint",
"*.{css, json, html}": "prettier"
},
```
TO-BE:
```json
"lint-staged": {
"*.{ts,tsx}": [
"eslint",
"prettier"
],
"*.{css,json,html}": "prettier"
},
```

[#58] Fix: lint-staged 설정 문제 해결

---

src/apis/auth/queryKey.ts
src/components/MyThreads/MyThreadBody.tsx
src/components/common/thread/ThreadListItem.tsx

유저 정보와 내가 쓴글을 커스텀 훅으로 받아오는 과정에서 생긴 예외처리와
커스텀parsing 함수를 사용하게 되며 발생하게 된 오류를 수정하였습니다.
close #68

[#68] Fix: getUserInfo 수정에 따른 내가 쓴 글 받아오기 변수 및 로직 변경

---

src/App.tsx
src/components/Demo/ExEditerTextArea.tsx

Cleanup: demo 삭제

---

src/apis/auth/queryFn.ts
src/apis/auth/useLogout.ts
src/apis/auth/usePostLogout.ts
src/components/Layout/Sidebar/view.tsx
src/utils/localStorage.ts

- 로그아웃 버튼 퍼블리싱 및 클릭 이벤트 생성
- 로그아웃 api 연결 및 훅 생성
- 로그아웃 성공 시 로컬 스토리지 토큰 삭제, 캐싱되어 있는 유저 정보 삭제
로그아웃 버튼 추가한 스크린샷 입니다.
편하게 리뷰 남겨주시면 감사하겠습니다!! :D
close #89

[#89] Feat: 로그아웃 기능 구현

---

src/apis/auth/usePostLogout.ts
src/components/Layout/Sidebar/view.tsx

로그인/로그아웃 성공 시 토스트 메시지 띄우기
- 급하게 코드를 짜서  편하게 리뷰 주시면 감사하겠습니다 :D
close #122

[#122] Feat: 로그인/로그아웃 토스트 메시지 띄우기

---

src/components/Layout/Sidebar/SidebarButton.tsx
src/components/Layout/Sidebar/view.tsx

사실 예전 PR에 올리고 싶었는데 조급해서 못 했네요,,ㅜㅜ 
사이드바에서 아래 구조가 반복되어 컴포넌트로 빼 리팩토링 했습니다.
```tsx
<button className={ButtonWrappingCSS} onClick={" "}>
<div className={cn("relative", IconWrappingCSS)}>
<LogIn className={IconCSS} />
</div>
<span className={IconDescriptionCSS}>로그인</span>
</button>
```
- 편하게 리뷰 주시면 감사하겠습니다 :D
close #128

[#128] Refactor: 사이드바 button 태그로 이루어진 아이콘 컴포넌트화

---

src/components/Layout/Modals/Login/index.tsx
src/components/Layout/Modals/Profile/index.tsx
src/components/Layout/Modals/Register/index.tsx
src/components/Layout/Sidebar/view.tsx
src/constants/toastMessage.ts
src/hooks/common/useToast.ts

재민님이 작업해주신 useToast 커스텀훅을 사용해서 리팩토링 했습니다.
showPromiseToast에 loading 메시지를 넣는 부분은 항상 고정된 문구를 사용해서 타입을 삭제했습니다!
- 편하게 리뷰해주시면 감사하겠습니다 :D
close #137

[#137] Refactor: toast 메시지 커스텀훅으로 변경

---

src/components/Home/ThreadList.tsx
src/components/common/EditorTextArea.tsx
src/components/common/thread/ThreadListItem.tsx
src/pages/Home/index.tsx

- 에디터 textarea에서 엔터시 submit 되도록 구현
- shift + enter시에는 제출 안되고 줄바꿈만 됨
- 글자 입력시 textarea 하단에 알림 문구 표시(스크린샷 참고)
- textarea에 값이 없다면 submit 안되도록 구현
- 스레드가 아래부터 쌓이도록 수정
- 스레드 추가시 스크롤 최하단으로 변경
마음껏 리뷰 부탁드립니다~~
`스레드 추가시 스크롤 최하단` => 이 부분 신경 쓰이는 점이 있습니다!
제가 스레드 추가할때는 스크롤이 최하단으로 가는게 자연스러운데, 타인이 스레드 추가해도 스크롤이 최하단으로 가는지 확인이 필요할 것 같아요
만약 타인이 추가해도 최하단으로 간다면 일이 조금 복잡해질 것 같습니다ㅠㅠ
close #141

[#141] Feat: 에디터에서 엔터시 submit 되도록 구현

---

src/components/common/EditorTextArea.tsx
src/components/common/thread/ThreadDetailView.tsx

여러 시도 끝에 결론은 
1. commentListItem h속성 삭제
2. editor 그냥 댓글 밑에 붙임
가 되었습니다.
close #148

[#148] Fix:긴 글 작성 시 스레드 자세히 보기 사이즈가 변경 됨 

---

src/components/Layout/Modals/Register/config.ts

이전 PR에서 커밋만 하고 push를 안해놓아 회원가입 이름 placeholder 문구 변경을 하지 않고 올라갔습니다.
다음부턴 조심하겠습니다.
close #152

[#152] Fix: 회원가입 이름 placeholder 문구 변경

---

.gitignore
package.json
src/components/Layout/Modals/Login/index.tsx
src/components/Layout/Modals/Profile/index.tsx
src/components/Layout/Modals/Register/index.tsx
src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
src/components/Layout/Sidebar/view.tsx
src/components/Layout/index.tsx
src/components/common/EditorTextArea.tsx
src/components/common/mention/MentionInput.tsx
src/components/common/thread/ThreadListItem.tsx
src/hooks/api/useEditorLogicByProps.ts
src/main.tsx
src/pages/Error/index.tsx
src/pages/Home/index.tsx
src/pages/MyNotifications/index.tsx
src/pages/MyThreads/index.tsx
src/pages/NotFound/index.tsx
vite.config.ts
yarn.lock

resolves #123 
- 프로젝트 전반에서 주요 행동을 로깅하는 구문을 넣었습니다.
- 오류 페이지를 넣었습니다.
- sentry 가입하시면 org 초대드릴게요.
- 개발 환경에서 환경 변수 추가 필요
- vercel env에 secret 추가 필요
- env에 secret 없어서 오류난 걸 거에요 (추가 후 re-deploy 필요)

[#123] Feat: Sentry 연동

---

src/components/common/thread/ThreadListItem.tsx

- 댓글만 바껴도 편집됨으로 뜨는거 삭제
close #159

[#159] Fix: 댓글 작성시 스레드에 '편집중' 추가는 이슈

---

src/components/MyNotifications/MyNotificationItem.tsx
src/components/MyThreads/MyThreadItem.tsx

내가 쓴 글과 알림에서도 건의게시판 채널이 매핑됩니다.
close #161

[#161] Feat: 내가 쓴 글 및 알람 건의 게시판 매핑

---

src/apis/comment/useDeleteComment.ts
src/apis/comment/usePostComment.ts
src/apis/mention/usePostMention.ts
src/apis/notification/usePostNotification.ts
src/apis/thread/useDeleteThread.ts
src/apis/thread/usePostThread.ts
src/apis/thread/usePostThreadLike.ts
src/apis/thread/usePutThread.ts
src/components/Layout/Modals/Login/index.tsx
src/components/Layout/Modals/Profile/index.tsx
src/components/Layout/Modals/Register/index.tsx
src/components/Layout/Sidebar/ThemeConfigDropdown.tsx
src/components/Layout/Sidebar/view.tsx
src/components/common/EditorTextArea.tsx
src/components/common/mention/MentionInput.tsx
src/components/common/thread/ThreadListItem.tsx
src/main.tsx
src/pages/Error/index.tsx
src/pages/Home/index.tsx
src/pages/MyNotifications/index.tsx
src/pages/MyThreads/index.tsx
src/pages/NotFound/index.tsx
src/utils/localStorage.ts
src/utils/logger.ts
src/utils/parsingJson.ts

resolves #163 
- 기존 Message를 info로 설정
- react-query의 query, mutation onError 기본 동작에서 captureException 추가

[#163] Sentry에서 react-query 오류도 보고되게 변경 

---

src/components/Layout/Sidebar/index.tsx

기존 사이드바에서 프로필에 무조건 '익프' 로 설정되던 부분에서 
이제는 닉네임이 반영됩니다.
close #166

[#166] Feat: 사이드바 프로필에 닉네임 반영

---

src/components/common/EditorTextArea.tsx
src/components/common/thread/ThreadDetailView.tsx
src/components/common/thread/ThreadListItem.tsx

- 익명 체크어부 기본값으로 수정 
- 편하게 말씀해주세요~!
close #171

[#171] Fix: 익명 체크여부 기본값 수정

---

src/components/Home/ChannelNavigationMenu.tsx

1. 잡단 게시판 드디어 증설👏👏👏
2. 채널이 많아지면서 동일한 태그가 반복되어 분리하게 되었습니다!
1. 잡담 게시판 네 번째 오는거 괜찮나요?
close #181

[#181] Feat: 잡담 게시판 추가

---

package.json
vite.config.ts
yarn.lock

resolves #197 
`VITE_GA4_ID=G-KRT5N7LL1H` 추가 - 개발 환경에서는 필요 없음
아래 부분도 env로 빼기
```js
sentryVitePlugin({
org: "jojaehun",
project: "javascript-react",
telemetry: false,
}),
```

[#197] Feat: Google Analytics 4 연동

---

src/components/common/mention/AutoCompleteMentionList.tsx
src/components/common/mention/MentionInput.tsx
src/components/common/mention/UserBadgeList.tsx

- 휴면에러였습니다,, 슬랫봇하다가 정신 놨었나봐요ㅎ,, 스미마셍
- 고치는김에 slackID라는 고유값이 추가되어 필터링 기준을 변경하였습니다. 
@Kim-Jaemin420 저번에 재준님이랑 같이 고쳤었던 고차함수 이름을 뭐라고 했었죠?? 
딱히 이름이 생각이안나 userList의 아이템값을 user로 했는데 좋은 네이밍 추천 받습니다!
close #210

[#210 ] Fix: 멘션 자동완성 클릭이벤트 미동작 에러

---

src/apis/thread/queryFn.ts
src/apis/thread/queryKey.ts
src/apis/thread/useGetThreads.ts
src/components/Home/ThreadList.tsx
src/hooks/api/useThreadsByChannel.ts
src/pages/Home/index.tsx

- 무한스크롤 부분이 배포환경에서만 작동하지 않아서 해당부분만 이전으로 롤백 
- 무한스크롤 부분만 따로 브랜치에서 배포 테스트 후 다시 머지 예정
close #212

 [#212] 무한스크롤 머지 이후 배포환경 정상작동 안하는 이슈 

---

index.html

resolves #204 
opengraph에 sitename을 `데나무숲`으로 지정

[#204] Chore: open graph - sitename 추가 

---

src/apis/thread/queryFn.ts
src/apis/thread/queryKey.ts
src/apis/thread/useDeleteThreadLike.ts
src/apis/thread/useGetThreads.ts
src/apis/thread/usePostThreadLike.ts
src/components/Home/ThreadList.tsx
src/components/common/thread/CommentListItem.tsx
src/components/common/thread/ThreadDetailView.tsx
src/components/common/thread/ThreadListItem.tsx
src/hooks/api/useThreadsByChannel.ts
src/pages/Home/index.tsx

1. 무한스크롤로 인해 데이터 타입이 변경되면서, 좋아요 반영 이슈가 생겼습니다.
무한 스크롤로 받아오는 데이터에 맞게 set하는 로직을 변경했습니다.
2. 이상하게도 ThreadList에서 reverse를 해주고 있는데, 로컬에서는 잘 작동하나 배포환경에서는 잘 작동하지 않는 문제가 있었습니다.
@jae-hun-e 디버깅의 신 갓갓갓님의 도움으로 reverse가 문제라는 것을 알게 되어 삭제 해주었습니다.
3. 로더의 위치와 스타일을 바꿔주었습니다.
gif를 참고해주세요!
보시면 아시겠지만, 다크 모드에서는 로딩 스타일이 문제가 없으나, 라이트 모드일때 에디터에는 배경 처리가 들어가지 않아서 에디터만 환하게 보입니다...
EditorTextArea에 className을 props로 줘서 해결해보려고 했는데 input 내부의 색상을 조작해야 하다 보니 방법이 생각보다 잘 떠오르지 않았습니다.
혹시 좋은 방법이 있다면 꼭 알려주세요!
close #209

[#209] Fix: 좋아요 반영 안되는 문제 해결 및 무한 스크롤 이슈 해결

---

.gitignore
src/hooks/api/useUpdateUserList.ts

- 에러처리 try catch로 감쌌습니다. 
에러처리 깔끔하게 하는 팁좀요,,, 굽신굽신
close #223

[#223] Fix: 유저정보 업데이트 실패시 에러처리 

---

src/components/MyNotifications/MyNotificationItem.tsx
src/components/MyThreads/MyThreadItem.tsx
src/components/common/thread/ThreadDetailView.tsx
src/types/channel.ts

잡담 게시판이 채널 매핑에 포함되지 않았어서 채널 매핑을 진행하였습니다.
close #221

[#221] Feat: 내가 쓴 글, 내 알림 채널 매핑
